Jingle/mui navigation
GalenWong/groundy pull request #13
Opened 2020-11-08 00:33 UTC by JingleH

2020-11-12 23:12 UTC, GalenWong requested changes

2020-11-12 23:12 UTC, GalenWong commented on test/features/counter/Counter.spec.tsx
> +// });
Delete all the commented out code. Just delete if we don't need them. The history are kept in git.

2020-11-12 23:27 UTC, JingleH commented on test/features/counter/Counter.spec.tsx
> +// });
Sure!

2020-11-12 23:31 UTC, GalenWong commented on test/features/counter/Counter.spec.tsx
> +// });
Don't forget the other files as well!

2020-11-14 20:12 UTC, GalenWong commented
super fun home page haha. nice animation

2020-11-14 20:12 UTC, merged