Upload PlaylistService.js and Authentication.js
GalenWong/groundy pull request #21
Opened 2020-11-22 01:52 UTC by andywdysj

Inside PlaylistService class there are 4 getter functions. All of them return raw json data directly from youtube, and modifications are needed in order to return Song object or Playlist object.

2020-11-22 03:20 UTC, GalenWong requested changes

2020-11-22 03:20 UTC, GalenWong commented on app/backend/PlaylistService.js
> +        const results = this.search(song)
calling the search seems like an overkill here. there is a simpler API to call for getting video info: https://developers.google.com/youtube/v3/docs/videos/list

2020-11-22 03:20 UTC, GalenWong commented on app/backend/PlaylistService.js
> +                Authorization: `${this.tokenType} ${this.accessToken}`,
getting a public playlist still requires user to login thru oauth. Can we use the API key instead so the user do not need to log in for this?

2020-11-23 04:33 UTC, andywdysj commented
Please review the updated version of this class!

2020-11-23 04:33 UTC, closed without merging